### ISSUE TITLE
` --max-async-wait-time` not supported in `import-solution` task

### ISSUE THREAD

**Issue by pkothare** [MicrosoftDocs/power-platform#1313]
I've been using the guidance from [Tutorial: Automate solution deployment using GitHub Actions for Microsoft Power Platform](https://docs.microsoft.com/en-us/power-platform/alm/tutorials/github-actions-deploy), and noticed that [release-solution-to-prod-with-inputs.yml](https://github.com/microsoft/powerplatform-actions-lab/blob/main/sample-workflows/release-solution-to-prod-with-inputs.yml) uses the `microsoft/powerplatform-actions/import-solution@0.4.0`.

When I run it in my environment, I noticed the error:

```
...
Error: The request channel timed out while waiting for a reply after 00:01:59.9990022.
 Increase the timeout value passed to the call to Request or increase the SendTimeout value on the Binding. 
The time allotted to this operation may have been a portion of a longer timeout.
    The request channel timed out while waiting for a reply after 00:01:59.9990022. 

The HTTP request to 'https://xxx.crm.dynamics.com/XRMServices/2011/Organization.svc/web?SDKClientVersion=9.0.46.3082'
 has exceeded the allotted timeout of 00:02:00. 
The time allotted to this operation may have been a portion of a longer timeout.
            The operation has timed out
...
```

The problem is that the `import-solution` task doesn't expose the `  --max-async-wait-time` parameter. What is the workaround, or is there a better way to address this error?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 6f60205c-d24f-9611-bb2f-bb635c7923c1
* Version Independent ID: f715289a-5ae2-872b-0b05-e5e0778cb061
* Content: [Available GitHub Actions for Microsoft Power Platform development - Power Platform](https://docs.microsoft.com/en-us/power-platform/alm/devops-github-available-actions)
* Content Source: [power-platform/alm/devops-github-available-actions.md](https://github.com/MicrosoftDocs/power-platform/blob/main/power-platform/alm/devops-github-available-actions.md)
* Service: **power-platform**
* Sub-service: **alm**
* GitHub Login: @kkanakas
* Microsoft Alias: **kartikka**

**Comment by bishalgoswami** [comment]
Thanks for your comment, @pkothare. This issue has been assigned to the doc author for review.

**Comment by pkothare** [comment]
@kkanakas, can you provide an example of how to use it?

```yml
...
- name: Import solution to prod environment
  uses: microsoft/powerplatform-actions/import-solution@v0
  with:
    environment-url: ${{env.ENVIRONMENT_URL}}
    app-id: ${{env.CLIENT_ID}}
    client-secret: ${{ secrets.PowerPlatformSPN }}
    tenant-id: ${{env.TENANT_ID}}
    solution-file: {{ github.event.inputs.solution_name }}_managed.zip
    max-async-wait-time: 15  # <--- what goes here minutes, seconds?
    force-overwrite: true
    publish-changes: true
...
```
