### ISSUE TITLE
Environment variables

### ISSUE THREAD

**Issue by kkazala** [MicrosoftDocs/power-platform#928]
I tried but ended up with empty values in the imported solution. Are there any special requirements for updating the variables? Is this approach setting current or default values?

In case of canvas apps with SP connections, the site url and list id is also embedded in the msapp file, even if I'm using variables rather than hardcoding the references. Will this approach also update them?

**Comment by kkazala** [comment]
hi @jimholtz 
Apologies for late reply, I was away for a few days. 

My yml file:
```
trigger:
- main

pool:
  vmImage: windows-latest

steps:
- task: PowerPlatformToolInstaller@0
  inputs:
    DefaultVersion: true
- checkout: self
  persistCredentials: true
    
- task: PowerPlatformImportSolution@0
  inputs:
    authenticationType: 'PowerPlatformSPN'
    PowerPlatformSPN: 'xxx'
    SolutionInputFile: '$(Build.SourcesDirectory)/PowerPlatform/Zips/LBA34TermineSync.zip'
    UseDeploymentSettingsFile: true
    DeploymentSettingsFile: '$(Build.SourcesDirectory)/PowerPlatform/Params/DeploymentSettings.Build.json'
    AsyncOperation: true
    MaxAsyncWaitTime: '60'
```

the settings file is present in the PowerPlatform/Params/ folder and has values (replacing guids with xxx below):
```
{
  "EnvironmentVariables": [
    {
      "SchemaName": "new_vGroupId",
      "Value": "xxx"
    },
    {
      "SchemaName": "new_vSharedEmail",
      "Value": "xxx"
    },
    {
      "SchemaName": "new_v_sp_Doc_Resources1",
      "Value": "xxx"
    },
    {
      "SchemaName": "new_v_sp_Doc_Resources2",
      "Value": "xxx"
    },
//  etc...
  ],
  "ConnectionReferences": [
    {
      "LogicalName": "new_connectionSMTP",
      "ConnectionId": "xxx",
      "ConnectorId": "/providers/Microsoft.PowerApps/apis/shared_smtp"
    },
    {
      "LogicalName": "new_sharedexcelonlinebusiness_b1ee3",
      "ConnectionId": "xxx",
      "ConnectorId": "/providers/Microsoft.PowerApps/apis/shared_excelonlinebusiness"
    },
    {
      "LogicalName": "new_sharedsharepointonline_67cc1",
      "ConnectionId": "shared-sharepointonl-xxx",
      "ConnectorId": "/providers/Microsoft.PowerApps/apis/shared_sharepointonline"
    },
    {
      "LogicalName": "new_sharedwebcontents_dc463",
      "ConnectionId": "xxx",
      "ConnectorId": "/providers/Microsoft.PowerApps/apis/shared_webcontents"
    }
  ]
}
```

After importing the solution, the environment variables don't have values assigned.
I'm preparing a new public repo right now to share it with you, but need to wait for a parallel job approval which may take a few days. Will share it as soon as it's working, I hope it will help :)

best regards
Kinga
